package pojo;
// Generated Dec 14, 2019 11:55:19 AM by Hibernate Tools 3.6.0



/**
 * AnswersHistory generated by hbm2java
 */
public class AnswersHistory  implements java.io.Serializable {


     private Integer idAnswersHistory;
     private PracticeQuestion practiceQuestion;
     private User user;
     private Answers answers;
     private String answer;
     private String type;

    public AnswersHistory() {
    }

    public AnswersHistory(PracticeQuestion practiceQuestion, User user, Answers answers, String answer, String type) {
       this.practiceQuestion = practiceQuestion;
       this.user = user;
       this.answers = answers;
       this.answer = answer;
       this.type = type;
    }
   
    public Integer getIdAnswersHistory() {
        return this.idAnswersHistory;
    }
    
    public void setIdAnswersHistory(Integer idAnswersHistory) {
        this.idAnswersHistory = idAnswersHistory;
    }
    public PracticeQuestion getPracticeQuestion() {
        return this.practiceQuestion;
    }
    
    public void setPracticeQuestion(PracticeQuestion practiceQuestion) {
        this.practiceQuestion = practiceQuestion;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Answers getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Answers answers) {
        this.answers = answers;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


