package pojo;
// Generated Dec 14, 2019 11:55:19 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * EnumSections generated by hbm2java
 */
public class EnumSections  implements java.io.Serializable {


     private Integer idenumsections;
     private EnumSubject enumSubject;
     private String title;
     private Set questions = new HashSet(0);

    public EnumSections() {
    }

	
    public EnumSections(EnumSubject enumSubject) {
        this.enumSubject = enumSubject;
    }
    public EnumSections(EnumSubject enumSubject, String title, Set questions) {
       this.enumSubject = enumSubject;
       this.title = title;
       this.questions = questions;
    }
   
    public Integer getIdenumsections() {
        return this.idenumsections;
    }
    
    public void setIdenumsections(Integer idenumsections) {
        this.idenumsections = idenumsections;
    }
    public EnumSubject getEnumSubject() {
        return this.enumSubject;
    }
    
    public void setEnumSubject(EnumSubject enumSubject) {
        this.enumSubject = enumSubject;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


