package pojo;
// Generated Dec 14, 2019 11:55:19 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * EnumQuestionStatus generated by hbm2java
 */
public class EnumQuestionStatus  implements java.io.Serializable {


     private Integer idenumquestionstatus;
     private String status;
     private Set questions = new HashSet(0);

    public EnumQuestionStatus() {
    }

    public EnumQuestionStatus(String status, Set questions) {
       this.status = status;
       this.questions = questions;
    }
   
    public Integer getIdenumquestionstatus() {
        return this.idenumquestionstatus;
    }
    
    public void setIdenumquestionstatus(Integer idenumquestionstatus) {
        this.idenumquestionstatus = idenumquestionstatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


