package pojo;
// Generated Dec 14, 2019 11:55:19 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PracticeQuestionSet generated by hbm2java
 */
public class PracticeQuestionSet  implements java.io.Serializable {


     private Integer idpracticeQuestionHistory;
     private QuestionSet questionSet;
     private User user;
     private Integer score;
     private Date insertTs;
     private Set practiceQuestions = new HashSet(0);

    public PracticeQuestionSet() {
    }

	
    public PracticeQuestionSet(QuestionSet questionSet, User user) {
        this.questionSet = questionSet;
        this.user = user;
    }
    public PracticeQuestionSet(QuestionSet questionSet, User user, Integer score, Date insertTs, Set practiceQuestions) {
       this.questionSet = questionSet;
       this.user = user;
       this.score = score;
       this.insertTs = insertTs;
       this.practiceQuestions = practiceQuestions;
    }
   
    public Integer getIdpracticeQuestionHistory() {
        return this.idpracticeQuestionHistory;
    }
    
    public void setIdpracticeQuestionHistory(Integer idpracticeQuestionHistory) {
        this.idpracticeQuestionHistory = idpracticeQuestionHistory;
    }
    public QuestionSet getQuestionSet() {
        return this.questionSet;
    }
    
    public void setQuestionSet(QuestionSet questionSet) {
        this.questionSet = questionSet;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
    public Date getInsertTs() {
        return this.insertTs;
    }
    
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }
    public Set getPracticeQuestions() {
        return this.practiceQuestions;
    }
    
    public void setPracticeQuestions(Set practiceQuestions) {
        this.practiceQuestions = practiceQuestions;
    }




}


