package pojo;
// Generated Dec 14, 2019 11:55:19 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PracticeQuestion generated by hbm2java
 */
public class PracticeQuestion  implements java.io.Serializable {


     private int idpracticeQuestion;
     private PracticeQuestionSet practiceQuestionSet;
     private String status;
     private Set answersHistories = new HashSet(0);

    public PracticeQuestion() {
    }

	
    public PracticeQuestion(int idpracticeQuestion, PracticeQuestionSet practiceQuestionSet) {
        this.idpracticeQuestion = idpracticeQuestion;
        this.practiceQuestionSet = practiceQuestionSet;
    }
    public PracticeQuestion(int idpracticeQuestion, PracticeQuestionSet practiceQuestionSet, String status, Set answersHistories) {
       this.idpracticeQuestion = idpracticeQuestion;
       this.practiceQuestionSet = practiceQuestionSet;
       this.status = status;
       this.answersHistories = answersHistories;
    }
   
    public int getIdpracticeQuestion() {
        return this.idpracticeQuestion;
    }
    
    public void setIdpracticeQuestion(int idpracticeQuestion) {
        this.idpracticeQuestion = idpracticeQuestion;
    }
    public PracticeQuestionSet getPracticeQuestionSet() {
        return this.practiceQuestionSet;
    }
    
    public void setPracticeQuestionSet(PracticeQuestionSet practiceQuestionSet) {
        this.practiceQuestionSet = practiceQuestionSet;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getAnswersHistories() {
        return this.answersHistories;
    }
    
    public void setAnswersHistories(Set answersHistories) {
        this.answersHistories = answersHistories;
    }




}


