package pojo;
// Generated Dec 14, 2019 11:55:19 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QuestionSet generated by hbm2java
 */
public class QuestionSet  implements java.io.Serializable {


     private Integer idquestionset;
     private EnumQuestionSetStatus enumQuestionSetStatus;
     private User user;
     private EnumSubject enumSubject;
     private String name;
     private Date initiateddate;
     private Set practiceQuestionSets = new HashSet(0);
     private Set questions = new HashSet(0);

    public QuestionSet() {
    }

	
    public QuestionSet(EnumQuestionSetStatus enumQuestionSetStatus, User user, EnumSubject enumSubject) {
        this.enumQuestionSetStatus = enumQuestionSetStatus;
        this.user = user;
        this.enumSubject = enumSubject;
    }
    public QuestionSet(EnumQuestionSetStatus enumQuestionSetStatus, User user, EnumSubject enumSubject, String name, Date initiateddate, Set practiceQuestionSets, Set questions) {
       this.enumQuestionSetStatus = enumQuestionSetStatus;
       this.user = user;
       this.enumSubject = enumSubject;
       this.name = name;
       this.initiateddate = initiateddate;
       this.practiceQuestionSets = practiceQuestionSets;
       this.questions = questions;
    }
   
    public Integer getIdquestionset() {
        return this.idquestionset;
    }
    
    public void setIdquestionset(Integer idquestionset) {
        this.idquestionset = idquestionset;
    }
    public EnumQuestionSetStatus getEnumQuestionSetStatus() {
        return this.enumQuestionSetStatus;
    }
    
    public void setEnumQuestionSetStatus(EnumQuestionSetStatus enumQuestionSetStatus) {
        this.enumQuestionSetStatus = enumQuestionSetStatus;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public EnumSubject getEnumSubject() {
        return this.enumSubject;
    }
    
    public void setEnumSubject(EnumSubject enumSubject) {
        this.enumSubject = enumSubject;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getInitiateddate() {
        return this.initiateddate;
    }
    
    public void setInitiateddate(Date initiateddate) {
        this.initiateddate = initiateddate;
    }
    public Set getPracticeQuestionSets() {
        return this.practiceQuestionSets;
    }
    
    public void setPracticeQuestionSets(Set practiceQuestionSets) {
        this.practiceQuestionSets = practiceQuestionSets;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


